# Generated by Django 5.1.6 on 2025-02-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_slider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the product.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='A detailed description of the product.')),
                ('short_description', models.CharField(blank=True, help_text='A brief summary of the product.', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product.', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of items available in stock.')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the product is currently available for purchase.')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the product title.', null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Title for SEO purposes (optional).', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines.', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the product was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image of the product.', upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image (for accessibility).', max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False, help_text='Whether this is the main image for the product.')),
                ('product', models.ForeignKey(help_text='The product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.product')),
            ],
        ),
    ]
